services:
  # Cấu hình cho Database Postgres
  ai-postgres:
    image: postgres:16
    container_name: ai-postgres
    environment:
      POSTGRES_DB: ai_agent_system
      POSTGRES_USER: huy
      POSTGRES_PASSWORD: 123
      TZ: Asia/Ho_Chi_Minh
    networks:
      - ai-network
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Cấu hình cho Spring Boot Backend
  ai-backend:
    build: .  # Chỉ định Docker build từ Dockerfile ở thư mục hiện tại
    container_name: ai-backend
    ports:
      - "8080:8080"
    environment:
      # LƯU Ý QUAN TRỌNG: Thay đổi localhost thành tên service 'ai-postgres'
      SPRING_DATASOURCE_URL: jdbc:postgresql://ai-postgres:5432/ai_agent_system?serverTimezone=Asia/Ho_Chi_Minh
      SPRING_DATASOURCE_USERNAME: huy
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - ai-postgres  # yêu cầu Docker bật DB trước rồi mới bật Backend sau
    networks:
      - ai-network

volumes:
  postgres_data:

networks:
  ai-network:
    driver: bridge